.TH  IRCMan 1 "15.06.2012" "Dominic Wanner" "documentation"
.UC
.SH "NAME"
ircbot - Startet einen IRC BOT
.SH "SYNOPSIS"
ircbot  [\fR \Server URL\fR] [\fR \Nickname URL\fR] [\fR \Channel URL\fR]
.SH "DESCRIPTION"
Um Den Bot starten zu können muss die Server URL, der Nickname sowie der Channel angegeben werden.
Der Bot selber läst sich dann über denn Channel lenken durch befehle.<br><br>
BOTNAME: BEFEHL "ZUSATZ"<br><br>
Es gibt folgende Befehle:<br>
LOG -> gibt gesammte Log aus
Start LOG -> startet Log führung (standart mässig an)
Stop LOG -> hält Log führung an
Last seen "NICKNAME" -> gibt alle Log einträge von NICKNAME aus
Stop - Stop den IrcBot und beendet die Anwendung 

